name: Build, scan and push to Docker Hub

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
      
jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Necessary for 'git describe' to work correctly

      - name: Set up version variable
        run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Call shared workflow to build and push Docker image
        uses: ukwa/ukwa-services/.github/workflows/push-to-docker-hub.yml@master
        with:
          image_name: ${{ github.repository }}
          version: ${{ env.VERSION }}
        secrets:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}